"""Subclass of modificarUsuario, which is generated by wxFormBuilder."""

import wx
import UI


# Implementing modificarUsuario
class ControlAccesosmodificarUsuario(UI.modificarUsuario):
    def __init__(self, parent):
        UI.modificarUsuario.__init__(self, parent)

    # Handlers for modificarUsuario events.
    def Regresar(self, event):
        from ControlAccesoslistadoFrame import ControlAccesoslistadoFrame

        self.Close()
        frame = ControlAccesoslistadoFrame(None)
        frame.Show(True)
        pass

    def AgregarPermisos(self, event):
        # TODO: Implement AgregarPermisos
        pass
