"""Subclass of autenticacionFrame, which is generated by wxFormBuilder."""

import wx
import UI
import pymysql.cursors
import config
from ControlAccesoslistadoFrame import ControlAccesoslistadoFrame


# Implementing autenticacionFrame
class ControlAccesosautenticacionFrame(UI.autenticacionFrame):
    def __init__(self, parent):
        UI.autenticacionFrame.__init__(self, parent)

    # Handlers for autenticacionFrame events.
    def obtenerDatosMySQL(self, event):
        # TODO: Implement obtenerDatosMySQL
        pass

    def iniciarSesion(self, event):
        try:
            connection = pymysql.connect(
                host="localhost",
                user=self.m_textCtrlUsuario.GetValue(),
                password=self.m_textCtrlContrasena.GetValue(),
                database="accesos",
                cursorclass=pymysql.cursors.DictCursor,
            )
            with connection:
                with connection.cursor() as cursor:
                    sql = "SELECT Insert_priv FROM mysql.user WHERE User = %s LIMIT 1;"
                    cursor.execute(sql, (self.m_textCtrlUsuario.GetValue(),))
            result = cursor.fetchone()

            # Verificar si se encontró un usuario con las credenciales ingresadas
            if result:
                config.usuario_actual = self.m_textCtrlUsuario.GetValue()
                config.contrasena_actual = self.m_textCtrlContrasena.GetValue()
                if result and result["Insert_priv"] == "Y":
                    config.admin = True
                else:
                    config.admin = False
                print(result)
                self.Close()
                frame = ControlAccesoslistadoFrame(None)
                frame.Show(True)
            else:
                print("Credenciales inválidas.")
        except Exception as e:
            print(f"Error al iniciar sesión: {str(e)}")
            self.mostrar_error("Credenciales inválidas, intente nuevamente.")

    def mostrar_error(self, mensaje):
        self.m_staticTextMensajeError.SetLabelText(mensaje)
        self.m_textCtrlUsuario.SetValue("")
        self.m_textCtrlContrasena.SetValue("")
        self.m_textCtrlUsuario.SetFocus()
        wx.CallLater(3000, self.ocultar_mensaje)

    def ocultar_mensaje(self):
        self.m_staticTextMensajeError.SetLabelText("")
