"""Subclass of listadoFrame, which is generated by wxFormBuilder."""

import wx
import UI
import pymysql.cursors
import config
from ControlAccesosdetalleFrame import ControlAccesosdetalleFrame


# Implementing listadoFrame
class ControlAccesoslistadoFrame(UI.listadoFrame):
    def __init__(self, parent):
        UI.listadoFrame.__init__(self, parent)

    # Handlers for listadoFrame events.
    def listarUsuarios(self, event):
        try:
            connection = pymysql.connect(
                host="localhost",
                user=config.usuario_actual,
                password=config.contrasena_actual,
                database="accesos",
                cursorclass=pymysql.cursors.DictCursor,
            )
            with connection:
                with connection.cursor() as cursor:
                    sql = """SELECT u.idusuario, u.nombreCompleto, u.usuarioAD, a.nombre AS area, p.nombre AS pais
							FROM usuario u
							INNER JOIN area a ON u.area = a.idarea
							INNER JOIN pais p ON u.pais = p.idpais;"""
                    cursor.execute(sql)
            result = cursor.fetchall()

            if result:
                print(result)
                self.m_gridUsuarios.SetColLabelValue(0, "idusuario")
                self.m_gridUsuarios.SetColLabelValue(1, "nombreCompleto")
                self.m_gridUsuarios.SetColLabelValue(2, "usuarioAD")
                self.m_gridUsuarios.SetColLabelValue(3, "area")
                self.m_gridUsuarios.SetColLabelValue(4, "pais")
                for i, result in enumerate(result):
                    self.m_gridUsuarios.SetCellValue(i, 0, str(result["idusuario"]))
                    self.m_gridUsuarios.SetCellValue(i, 1, result["nombreCompleto"])
                    self.m_gridUsuarios.SetCellValue(i, 2, result["usuarioAD"])
                    self.m_gridUsuarios.SetCellValue(i, 3, result["area"])
                    self.m_gridUsuarios.SetCellValue(i, 4, result["pais"])
                self.m_gridUsuarios.AutoSizeColumns()
            else:
                print("Error al listarUsuarios")
        except Exception as e:
            print(f"Error en listarUsuarios: {str(e)}")

    def Buscar(self, event):
        # TODO: Implement Buscar
        pass

    def mostrarDetalle(self, event):
        selected_row = self.m_gridUsuarios.GetSelectedRows()[0]

        # Obtener el valor de la columna "usuarioAD" correspondiente a la fila seleccionada
        usuario_ad = self.m_gridUsuarios.GetCellValue(selected_row, 2)

        # Imprimir el valor obtenido
        print(usuario_ad)
        self.Close()
        frame = ControlAccesosdetalleFrame(None)
        frame.Show(True)
