"""Subclass of panelDeControl, which is generated by wxFormBuilder."""

import wx
import UI


# Implementing panelDeControl
class ControlAccesospanelDeControl(UI.panelDeControl):
    def __init__(self, parent):
        UI.panelDeControl.__init__(self, parent)

    # Handlers for panelDeControl events.
    def Regresar(self, event):
        from ControlAccesoslistadoFrame import ControlAccesoslistadoFrame

        self.Close()
        frame = ControlAccesoslistadoFrame(None)
        frame.Show(True)

    def CrearUsuario(self, event):
        # TODO: Implement CrearUsuario
        pass
