"""Subclass of panelDeControl, which is generated by wxFormBuilder."""

import config
import UI
import wx


# Implementing panelDeControl
class ControlAccesospanelDeControl(UI.panelDeControl):
    def __init__(self, parent):
        UI.panelDeControl.__init__(self, parent)

    # Handlers for panelDeControl events.
    def inicializarPanelDeControl(self, event):
        # llenar comboBox Pais
        datosPais = config.ejecutarQueryLectura("""SELECT nombre AS pais FROM pais;""")
        if datosPais:
            for i, item in enumerate(datosPais):
                self.m_comboBoxPais.Append(item["pais"])
        else:
            print("Error al listar Combobox pais")

        # llenar comboBox Area
        datosArea = config.ejecutarQueryLectura("""SELECT nombre AS area FROM area;""")
        if datosArea:
            for j, item in enumerate(datosArea):
                self.m_comboBoxArea.Append(item["area"])
        else:
            print("Error al listar Combobox area")
        pass

    def Regresar(self, event):
        from ControlAccesoslistadoFrame import ControlAccesoslistadoFrame

        self.Close()
        frame = ControlAccesoslistadoFrame(None)
        frame.Show(True)

    def CrearUsuario(self, event):
        config.ejecutarQueryInsert(
            """
				INSERT INTO usuario (nombreCompleto, usuarioAD, area, pais)
				VALUES (%s, %s, (SELECT idarea FROM area WHERE nombre = %s), (SELECT idpais FROM pais WHERE nombre = %s));
			""",
            (
                self.m_textCtrlNombreCompleto.GetValue(),
                self.m_textCtrlActiveDirectory.GetValue(),
                self.m_comboBoxArea.GetValue(),
                self.m_comboBoxPais.GetValue(),
            ),
        )

        IDusuarioRecienCreado = config.ejecutarQueryLectura(
            """SELECT idusuario FROM usuario where usuarioAD = %s;""",
            self.m_textCtrlActiveDirectory.GetValue(),
        )

        config.usuarioSeleccionado = self.m_textCtrlActiveDirectory.GetValue()
        config.IDusuarioSeleccionado = IDusuarioRecienCreado[0]["idusuario"]
        config.usuarioSeleccionadoNombreCompleto = (
            self.m_textCtrlNombreCompleto.GetValue()
        )
        self.Close()
        from ControlAccesosdetalleFrame import ControlAccesosdetalleFrame

        frame = ControlAccesosdetalleFrame(None)
        frame.Show(True)

    def validarBotonCrear(self, event):
        # el boton Crear usuario solo se activara si todos los text_ctrl tienen un valor
        text_ctrls = [
            control
            for control in self.GetChildren()
            if isinstance(control, wx.TextCtrl)
        ]
        enable_button = all(len(text_ctrl.GetValue()) > 1 for text_ctrl in text_ctrls)

        self.m_buttonCrearUsuario.Enable(enable_button)
